<div class="w3-container" id="showcase">
  <h1 class="w3-xxxlarge w3-text-dark-grey w3-center"><b>Főoldal</b></h1>
</div>

<div class="w3-row-padding">
  <div class="w3-col s12 m4 l4">
    <a href="/szerzok">
      <div class="w3-container w3-red w3-hover-dark-red w3-padding-16 w3-card-4">
        <div class="w3-left"><i class="fa fa-pencil w3-xxxlarge"></i></div>
        <div class="w3-right">
          <h3><?= count($params["authors"]) ?></h3>
        </div>
        <div class="w3-clear"></div>
        <h4>Szerzők</h4>
      </div>
    </a>
  </div>
  <div class="w3-col s12 m4 l4">
    <a href="/konyvek">
      <div class="w3-container w3-green w3-hover-dark-green w3-padding-16 w3-card-4">
        <div class="w3-left"><i class="fa fa-book w3-xxxlarge"></i></div>
        <div class="w3-right">
          <h3><?= count($params["books"]) ?></h3>
        </div>
        <div class="w3-clear"></div>
        <h4>Könyvek</h4>
      </div>
    </a>
  </div>
  <div class="w3-col s12 m4 l4">
    <a href="/kategoriak">
      <div class="w3-container w3-blue w3-hover-dark-blue w3-padding-16 w3-card-4">
        <div class="w3-left"><i class="fa fa-list w3-xxxlarge"></i></div>
        <div class="w3-right">
          <h3><?= count($params["categories"]) ?></h3>
        </div>
        <div class="w3-clear"></div>
        <h4>Kategóriák</h4>
      </div>
    </a>
  </div>
</div>

<div class="w3-row-padding w3-margin-bottom w3-centered">
  <div class="w3-col s12 m6 l6">
    <a href="/kolcsonzesek">
      <div class="w3-container w3-teal w3-hover-dark-teal w3-padding-16 w3-card-4">
        <div class="w3-left"><i class="fa fa-exchange w3-xxxlarge"></i></div>
        <div class="w3-right">
          <h3><?= count($params["borrows"]) ?></h3>
        </div>
        <div class="w3-clear"></div>
        <h4>Kölcsönzések</h4>
      </div>
    </a>
  </div>
  <div class="w3-col s12 m6 l6">
    <a href="/olvasok">
      <div class="w3-container w3-orange w3-hover-dark-orange w3-text-white w3-padding-16 w3-card-4">
        <div class="w3-left"><i class="fa fa-users w3-xxxlarge"></i></div>
        <div class="w3-right">
          <h3><?= count($params["readers"]) ?></h3>
        </div>
        <div class="w3-clear"></div>
        <h4>Olvasók</h4>
      </div>
    </a>
  </div>
</div>

<!-- Kölcsönzések -->
<div class="w3-container  w3-margin-bottom">
  <h2 class="">Kölcsönzések</h2>
  <div class="w3-responsive w3-card-4 w3-round-large">
    <table class="w3-table w3-striped w3-bordered w3-border w3 w3-white w3-centered">
      <thead class="w3-dark-grey">
        <th style="width: 10%;">#</th>
        <th style="width: 20%;">Cím</th>
        <th style="width: 20%;">Olvasó</th>
        <th style="width: 30%;">Kivette</th>
        <th style="width: 30%;">Határidő</th>
        <th style="width: 10%;">Visszahozva</th>
        <th style="width: 10%;"></th>
      </thead>
      <tbody>
        <?php foreach ($params["borrows"] as $borrow) : ?>
          <tr>
            <td><?= $borrow["id"] ?></td>
            <td><?= $borrow["book"] ?></td>
            <td><?= $borrow["reader"] ?></td>
            <td><?= $borrow["borrow_date"] ?></td>
            <td><?= $borrow["due_date"] ?></td>
            <?php if (!is_null($borrow["return_date"])) : ?>
              <td><?= $borrow["return_date"] ?></td>
            <?php else : ?>
              <td>
                <form action="/kolcsonzes-visszahozva/<?= $borrow["id"] ?>" method="POST">
                  <input type="hidden" value="<?= $borrow["book_id"] ?>">
                  <button type="submit" href="kolcsonzes-visszahozva/<?= $borrow["id"] ?>" class="w3-button w3-border w3-padding-small w3-grey w3-hover-dark-grey w3-round">
                    <i class="fa fa-undo w3-xlarge"></i></a>
                </form>
              </td>
            <?php endif; ?>
            <td>
              <a href="/kolcsonzes-szerkesztese/<?= $borrow['id'] ?>"" class=" w3-button w3-border w3-orange w3-round w3-padding-small w3-hover-dark-orange w3-text-center">
                <i class="fa fa-pencil w3-xlarge"></i>
              </a>
            </td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
  <br>
  <div class="w3-center">
    <a href="/kolcsonzesek" class="w3-button w3-border w3-grey w3-hover-dark-grey w3-round">Kölcsönzések &nbsp;<i class="fa fa-arrow-right"></i></a>
  </div>
</div>

<!-- Olvasók -->
<div class="w3-container  w3-margin-bottom">
  <h2 class="">Olvasók</h2>
  <div class="w3-responsive w3-card-4 w3-round-large">
    <table class="w3-table w3-striped w3-bordered w3-border w3 w3-white w3-centered">
      <thead class="w3-dark-grey">
        <th style="width: 10%;">#</th>
        <th style="width: 20%;">Név</th>
        <th style="width: 20%;">Email</th>
        <th style="width: 20%;">Telefon</th>
        <th style="width: 10%;">Cím</th>
        <th style="width: 10%;">Csatlakozott</th>
        <th style="width: 10%;"></th>
      </thead>
      <tbody>
        <?php foreach ($params["readers"] as $reader) : ?>
          <tr>
            <td><?= $reader["id"] ?></td>
            <td><?= $reader["lastName"] . " " . $reader["firstName"] ?></td>
            <td><?= $reader["email"] ?></td>
            <td><?= $reader["mobile"] ?></td>
            <td><?= $reader["address"] ?></td>
            <td><?= date("Y-m-d", strtotime($reader["joined_at"])); ?></td>
            <td class="">
              <a href="olvaso/<?= $reader["id"] ?>" class="w3-button w3-blue w3-border w3-border-blue w3-round w3-padding-small w3-hover-dark-blue w3-text-center">
                <i class="fa fa-eye w3-xlarge"></i>
              </a>
              <a href="olvaso-szerkesztese/<?= $reader["id"] ?>" class="w3-button w3-orange w3-border w3-round w3-padding-small w3-hover-dark-orange w3-text-center" href="">
                <i class="fa fa-pencil w3-xlarge"></i>
              </a>
            </td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
  <br>
  <div class="w3-center">
    <a href="/olvasok" class="w3-button w3-border w3-grey w3-hover-dark-grey w3-round">Olvasók &nbsp;<i class="fa fa-arrow-right"></i></a>
  </div>
</div>

<!-- Könyvek -->
<div class="w3-container  w3-margin-bottom">
<h2 class="">Könyvek</h2>
    <div class="w3-responsive w3-card-4 w3-round-large">
        <table class="w3-table w3-striped w3-bordered w3-border w3 w3-white  w3-centered">
            <thead class="w3-dark-grey">
                <th style="width: 10%;">#</th>
                <th style="width: 20%;">Cím</th>
                <th style="width: 20%;">Szerző</th>
                <th style="width: 30%;">Kategóriák</th>
                <th style="width: 10%;">Kikölcsönözve</th>
                <th style="width: 10%;"></th>
            </thead>
            <tbody>
                <?php foreach ($params["books"] as $book) : ?>
                    <tr>
                        <td><?= $book["id"] ?></td>
                        <td><?= $book["title"] ?></td>
                        <td><?= $book["author"] ?></td>
                        <td><?= $book["categories"] ?></td>
                        <td><?= $book["isBorrowed"] ? "Igen" : "Nem" ?></td>
                        <td class="">
                            <a href="konyv/<?= $book["id"] ?>" class="w3-button w3-blue w3-border  w3-round w3-padding-small w3-hover-dark-blue w3-text-center">
                                <i class="fa fa-eye w3-xlarge"></i>
                            </a>
                            <a href="konyv-szerkesztese/<?= $book["id"] ?>" class="w3-button w3-orange w3-border w3-round w3-padding-small w3-hover-dark-orange w3-text-center" href="">
                                <i class="fa fa-pencil w3-xlarge"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <br>
  <div class="w3-center">
    <a href="/konyvek" class="w3-button w3-border w3-grey w3-hover-dark-grey w3-round">Könyvek &nbsp;<i class="fa fa-arrow-right"></i></a>
  </div>
</div>