<div class="w3-container  w3-margin-bottom-32" id="showcase">
    <h1 class="w3-xxxlarge w3-text-dark-grey w3-center"><b>Kategoria Módosítás</b></h1>
</div>

<div class="w3-container w3-margin-bottom">
    <div class="w3-responsive w3-card-4 w3-round-large">
        <header class="w3-container w3-dark-grey">
            <h2>Adatok</h2>
        </header>
        <form class="w3-container w3-card-4" method="POST" action="/kategoria-szerkesztese/<?= $params["category"]["id"] ?>">
            <br>
            <p>
                <label class="w3-show-inline-block w3-margin-bottom-8">Név</label>
                <input class="w3-input w3-border" type="text" name="name" value="<?= $params["category"]["name"] ?>"  required="">
            </p>
            <p class="w3-text-center">
                <button type="submit" class="w3-button w3-border w3-text-orange w3-border-orange w3-hover-orange w3-round w3-block">Módosítás</button>
            </p>
        </form>
    </div>
</div>