<div class="w3-container  w3-margin-bottom-32" id="showcase">
    <h1 class="w3-xxxlarge w3-text-dark-grey w3-center"><b>Kölcsönzések</b></h1>
</div>

<form action="/kereses" method="GET">
    <div class="w3-row-padding w3-margin-bottom">
        <div class="w3-third">
            <input class="w3-input w3-border w3-round " type="text" placeholder="Könyv címe">
        </div>
        <div class="w3-third">
            <button class="w3-button w3-border w3-blue  w3-hover-dark-blue w3-round w3-block"><i class="fa fa-search w3-margin-right"></i>Keresés</button>
        </div>
        <div class="w3-third">
            <a href="/uj-kolcsonzes" class="w3-button w3-border w3-green  w3-hover-dark-green w3-round w3-block"><i class="fa fa-plus w3-margin-right"></i>Új kölcsönzés</a>
        </div>
    </div>
</form>

<div class="w3-container  w3-margin-bottom">
    <div class="w3-responsive w3-card-4 w3-round-large">
        <table class="w3-table w3-striped w3-bordered w3-border w3 w3-white w3-centered">
            <thead class="w3-dark-grey">
                <th style="width: 10%;">#</th>
                <th style="width: 20%;">Cím</th>
                <th style="width: 20%;">Olvasó</th>
                <th style="width: 30%;">Kivette</th>
                <th style="width: 30%;">Határidő</th>
                <th style="width: 10%;">Visszahozva</th>
                <th style="width: 10%;"></th>
            </thead>
            <tbody>
                <?php foreach ($params["borrows"] as $borrow) : ?>
                    <tr>
                        <td><?= $borrow["id"] ?></td>
                        <td><?= $borrow["book"] ?></td>
                        <td><?= $borrow["reader"] ?></td>
                        <td><?= $borrow["borrow_date"] ?></td>
                        <td><?= $borrow["due_date"] ?></td>
                        <?php if (!is_null($borrow["return_date"])) : ?>
                            <td><?= $borrow["return_date"] ?></td>
                        <?php else : ?>
                            <td>
                                <form action="/kolcsonzes-visszahozva/<?= $borrow["id"] ?>" method="POST">
                                    <input type="hidden" value="<?= $borrow["book_id"] ?>">
                                    <button type="submit" href="kolcsonzes-visszahozva/<?= $borrow["id"] ?>" class="w3-button w3-border w3-padding-small w3-grey w3-hover-dark-grey w3-round">
                                        <i class="fa fa-undo w3-xlarge"></i></a>
                                </form>
                            </td>
                        <?php endif; ?>
                        <td>
                            <a href="/kolcsonzes-szerkesztese/<?= $borrow['id'] ?>"" class=" w3-button w3-border w3-orange w3-round w3-padding-small w3-hover-dark-orange w3-text-center">
                                <i class="fa fa-pencil w3-xlarge"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>