
<div class="w3-container  w3-margin-bottom-32" id="showcase">
    <h1 class="w3-xxxlarge w3-text-dark-grey w3-center"><b>Könyv</b></h1>
</div>

<div class="w3-container w3-margin-bottom">
    <div class="w3-responsive w3-card-4 w3-round-large">
        <header class="w3-container w3-dark-grey">
            <h2>Adatok</h2>
        </header>
        <div class="w3-row-padding w3-margin-bottom">
            <div class="w3-col s12 m4 l4">
                <h4><b>Cím:</b></h4>
            </div>
            <div class="w3-col s12 m8 l8">
                <h4><?= $params["book"]["title"] ?></h4>
            </div>
            <div class="w3-col s12 m4 l4">
                <h4><b>Szerző:</b></h4>
            </div>
            <div class="w3-col s12 m8 l8">
                <h4><?= $params["book"]["author"]  ?></h4>
            </div>
            <div class="w3-col s12 m4 l4">
                <h4><b>Leírás:</b></h4>
            </div>
            <div class="w3-col s12 m8 l8">
                <p><?= $params["book"]["description"]  ?></p>
            </div>
            <div class="w3-col s12 m4 l4">
                <h4><b>Megjelenés:</b></h4>
            </div>
            <div class="w3-col s12 m8 l8">
                <h4><?= $params["book"]["published"]  ?></h4>
            </div>
            <div class="w3-col s12 m4 l4">
                <h4><b>Kategóriák:</b></h4>
            </div>
            <div class="w3-col s12 m8 l8">
                <h4><?= $params["book"]["categories"] ?></h4>
            </div>
            <div class="w3-col s12 m4 l4">
                <h4><b>Borító:</b></h4>
            </div>
            <div class="w3-col s12 m8 l8">
                <img src="/public/<?= $params["book"]["cover_url"] ?>" alt="" style="max-height: 200px;">
            </div>
            <div class="w3-col s12 m4 l4">
                <h4><b>Kölcsönzések:</b></h4>
            </div>
            <div class="w3-col s12 m8 l8">
                <h4><?= count($params["borrows"]) ?></h4>
            </div>
            <div class="w3-col s12 m4 l4">
                <h4><b>Állapot:</b></h4>
            </div>
            <div class="w3-col s12 m8 l8">
                <h4 class="<?= $params["book"]["isBorrowed"] ? "w3-text-red" : "" ?>"><?= $params["book"]["isBorrowed"] ? "Kikölcsönözve" : "Visszahozva" ?></h4>
            </div>
        </div>
    </div>
</div>

<div class="w3-container  w3-margin-bottom-32" id="showcase">
    <h2 class="w3-xxxlarge w3-text-dark-grey w3-center"><b>Kölcsönzések</b></h2>
</div>

<div class="w3-container  w3-margin-bottom">
    <div class="w3-responsive w3-card-4 w3-round-large">
        <table class="w3-table w3-striped w3-bordered w3-border w3 w3-white ">
            <thead class="w3-dark-grey">
                <th style="width: 10%;">#</th>
                <th style="width: 20%;">Cím</th>
                <th style="width: 20%;">Olvasó</th>
                <th style="width: 30%;">Kivette</th>
                <th style="width: 30%;">Határidő</th>
                <th style="width: 10%;">Visszahozva</th>
                <th style="width: 10%;"></th>
            </thead>
            <tbody>
                <?php foreach ($params["borrows"] as $borrow) : ?>
                    <tr>
                        <td><?= $borrow["id"] ?></td>
                        <td><?= $borrow["book_title"] ?></td>
                        <td><?= $borrow["reader_name"] ?></td>
                        <td><?= $borrow["borrow_date"] ?></td>
                        <td><?= $borrow["due_date"] ?></td>
                        <?php if (!is_null($borrow["return_date"])) : ?>
                            <td><?= $borrow["return_date"] ?></td>
                        <?php else : ?>
                            <td>
                                <form action="/kolcsonzes-visszahozva/<?= $borrow["id"] ?>" method="POST">
                                    <input type="hidden" value="<?= $borrow["book_id"] ?>">
                                    <button type="submit" href="kolcsonzes-visszahozva/<?= $borrow["id"] ?>" class="w3-button w3-border w3-padding-small w3-grey w3-hover-dark-grey w3-round">
                                        <i class="fa fa-undo w3-xlarge"></i></a>
                                </form>
                            </td>
                        <?php endif; ?>
                        <td>
                            <a href="/kolcsonzes-szerkesztese/<?= $borrow['id'] ?>"" class=" w3-button w3-border w3-orange w3-round w3-padding-small w3-hover-dark-orange w3-text-center">
                                <i class="fa fa-pencil w3-xlarge"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>