<div class="w3-container  w3-margin-bottom-32" id="showcase">
    <h1 class="w3-xxxlarge w3-text-dark-grey w3-center"><b>Olvasók</b></h1>
</div>

<form action="/kereses" method="GET">
    <div class="w3-row-padding w3-margin-bottom">
        <div class="w3-third">
            <input class="w3-input w3-border w3-round " type="text" placeholder="Olvasó Neve">
        </div>
        <div class="w3-third">
            <button class="w3-button w3-border w3-blue w3-hover-dark-blue w3-round w3-block"><i class="fa fa-search w3-margin-right"></i>Keresés</button>
        </div>
        <div class="w3-third">
            <a href="/uj-olvaso" class="w3-button w3-border w3-green w3-hover-dark-green w3-round w3-block"><i class="fa fa-plus w3-margin-right"></i>Új Olvasó</a>
        </div>
    </div>
</form>

<div class="w3-container  w3-margin-bottom">
    <div class="w3-responsive w3-card-4 w3-round-large">
        <table class="w3-table w3-striped w3-bordered w3-border w3 w3-white ">
            <thead class="w3-dark-grey">
                <th style="width: 10%;">#</th>
                <th style="width: 20%;">Név</th>
                <th style="width: 20%;">Email</th>
                <th style="width: 20%;">Telefon</th>
                <th style="width: 10%;">Cím</th>
                <th style="width: 10%;">Csatlakozott</th>
                <th style="width: 10%;"></th>
            </thead>
            <tbody>
                <?php foreach ($params["readers"] as $reader) : ?>
                    <tr>
                        <td><?= $reader["id"] ?></td>
                        <td><?= $reader["lastName"] . " " . $reader["firstName"] ?></td>
                        <td><?= $reader["email"] ?></td>
                        <td><?= $reader["mobile"] ?></td>
                        <td><?= $reader["address"] ?></td>
                        <td><?= date("Y-m-d", strtotime($reader["joined_at"])); ?></td>
                        <td class="">
                            <a href="olvaso/<?= $reader["id"] ?>" class="w3-button w3-blue w3-border w3-border-blue w3-round w3-padding-small w3-hover-dark-blue w3-text-center">
                                <i class="fa fa-eye w3-xlarge"></i>
                            </a>
                            <a href="olvaso-szerkesztese/<?= $reader["id"] ?>" class="w3-button w3-orange w3-border w3-round w3-padding-small w3-hover-dark-orange w3-text-center" href="">
                                <i class="fa fa-pencil w3-xlarge"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>