<div class="w3-container  w3-margin-bottom-32" id="showcase">
    <h1 class="w3-xxxlarge w3-text-dark-grey w3-center"><b>Olvasó</b></h1>
</div>

<div class="w3-container w3-margin-bottom">
    <div class="w3-responsive w3-card-4 w3-round-large">
        <header class="w3-container w3-dark-grey">
            <h2>Adatok</h2>
        </header>
        <div class="w3-row-padding w3-margin-bottom">
            <div class="w3-third">
                <h4><b>Név:</b></h4>
            </div>
            <div class="w3-twothird">
                <h4><?= $params["reader"]["lastName"] . " " . $params["reader"]["firstName"] ?></h4>
            </div>
            <div class="w3-third">
                <h4><b>Email:</b></h4>
            </div>
            <div class="w3-twothird">
                <h4><?= $params["reader"]["email"] ?></h4>
            </div>
            <div class="w3-third">
                <h4><b>Mobil:</b></h4>
            </div>
            <div class="w3-twothird">
                <h4><?= $params["reader"]["mobile"] ?></h4>
            </div>
            <div class="w3-third">
                <h4><b>Cím:</b></h4>
            </div>
            <div class="w3-twothird">
                <h4><?= $params["reader"]["address"] ?><h4>
            </div>
            <div class="w3-third">
                <h4><b>Csatlakozott:</b></h4>
            </div>
            <div class="w3-twothird">
                <h4><?= date("Y-m-d", strtotime($params["reader"]["joined_at"])); ?></h4>
            </div>

        </div>
    </div>
</div>

<div class="w3-container  w3-margin-bottom-32" id="showcase">
    <h2 class="w3-xxxlarge w3-text-dark-grey w3-center"><b>Kölcsönzések</b></h2>
</div>

<div class="w3-container w3-margin-bottom">
    <div class="w3-responsive w3-card-4 w3-round-large">
        <table class="w3-table w3-striped w3-bordered w3-border w3 w3-white ">
            <thead class="w3-dark-grey">
                <th style="width: 10%;">#</th>
                <th style="width: 20%;">Cím</th>
                <th style="width: 30%;">Kölcsönzési Dátum</th>
                <th style="width: 30%;">Határidő</th>
                <th style="width: 10%;">Visszahozva</th>
            </thead>
            <tbody>
                <tr>
                    <td>3</td>
                    <td>A kis herceg</td>
                    <td>2020-04-10</td>
                    <td>2020-05-10</td>
                    <td class="">
                        <a class="w3-button w3-border w3-border-dark-grey w3-hover-dark-grey w3-round">Visszahozva
                            &nbsp;<i class="fa fa-arrow-right"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>A gyűrűk ura</td>
                    <td>2020-03-02</td>
                    <td>2020-04-02</td>
                    <td>2020-04-02</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Vuk</td>
                    <td>2020-01-30</td>
                    <td>2020-03-01</td>
                    <td>2020-02-25</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>