<div class="w3-container  w3-margin-bottom-32" id="showcase">
    <h1 class="w3-xxxlarge w3-text-dark-grey w3-center"><b>Olvasó Módosítás</b></h1>
</div>

<div class="w3-container w3-margin-bottom">
    <div class="w3-responsive w3-card-4 w3-round-large">
        <header class="w3-container w3-dark-grey">
            <h2>Adatok</h2>
        </header>
        <form class="w3-container w3-card-4" method="POST" action="/olvaso-szerkesztese/<?= $params["reader"]["id"] ?>">
            <br>
            <p>
                <label class="w3-show-inline-block w3-margin-bottom-8">Vezetéknév</label>
                <input class="w3-input w3-border" type="text" name="lastName" value="<?= $params["reader"]["lastName"] ?>" required>
            </p>
            <p>
                <label class="w3-show-inline-block w3-margin-bottom-8">Keresztnév</label>
                <input class="w3-input w3-border" type="text" name="firstName" value="<?= $params["reader"]["firstName"] ?>" required>
            </p>
            <p>
                <label class="w3-show-inline-block w3-margin-bottom-8">Email</label>
                <input class="w3-input w3-border" type="email" name="email" value="<?= $params["reader"]["email"] ?>" required>
            </p>
            <p>
                <label class="w3-show-inline-block w3-margin-bottom-8">Mobil</label>
                <input class="w3-input w3-border" type="tel" pattern="[0-9]{2}/[0-9]{3}-[0-9]{4}" placeholder="20/254-4324" name="mobile" value="<?= $params["reader"]["mobile"] ?>" required>
            </p>
            <p>
                <label class="w3-show-inline-block w3-margin-bottom-8">Cím</label>
                <input class="w3-input w3-border" type="text" name="address" value="<?= $params["reader"]["address"] ?>" required>
            </p>
            <p class="w3-text-center">
                <button type="submit" class="w3-button w3-border w3-orange  w3-hover-dark-orange w3-round w3-block">Módosítás</button>
            </p>
        </form>
    </div>
</div>