<div class="w3-container  w3-margin-bottom-32" id="showcase">
    <h1 class="w3-xxxlarge w3-text-dark-grey w3-center"><b>Szerző</b></h1>
</div>

<div class="w3-container w3-margin-bottom">
    <div class="w3-responsive w3-card-4 w3-round-large">
        <header class="w3-container w3-dark-grey">
            <h2>Adatok</h2>
        </header>
        <div class="w3-row-padding w3-margin-bottom">
            <div class="w3-third">
                <h4><b>Név:</b></h4>
            </div>
            <div class="w3-twothird">
                <h4><?= $params["author"]["name"] ?></h4>
            </div>
            <div class="w3-third">
                <h4><b>Életrajz:</b></h4>
            </div>
            <div class="w3-twothird">
                <p><?= $params["author"]["bio"] ?>
                <p>
            </div>
            <div class="w3-third">
                <h4><b>Könyvek:</b></h4>
            </div>
            <div class="w3-twothird">
                <h4><?= count($params["author"]["books"]) ?></h4>
            </div>
        </div>
    </div>
</div>

<div class="w3-container  w3-margin-bottom-32" id="showcase">
    <h2 class="w3-xxxlarge w3-text-dark-grey w3-center"><b>Könyvek</b></h2>
</div>

<div class="w3-container  w3-margin-bottom">
    <div class="w3-responsive w3-card-4 w3-round-large">
        <table class="w3-table w3-striped w3-bordered w3-border w3 w3-white ">
            <thead class="w3-dark-grey">
                <th style="width: 10%;">#</th>
                <th style="width: 20%;">Cím</th>
                <th style="width: 20%;">Kategóriák</th>
                <th style="width: 20%;">Oldal</th>
                <th style="width: 20%;">Kikölcsönözve</th>
                <th style="width: 10%;"></th>
            </thead>
            <tbody>
                <?php foreach ($params["author"]["books"] as $book) : ?>
                    <tr>
                        <td><?= $book["id"] ?></td>
                        <td><?= $book["title"] ?></td>
                        <td><?= $book["categories"] ?></td>
                        <td><?= $book["pages"] ?></td>
                        <td><?= $book["isBorrowed"] ? "Igen" : "Nem" ?></td>
                        <td class="w3-center">
                            <a href="/konyv/<?= $book["id"] ?>" class="w3-button w3-text-blue w3-border w3-border-blue w3-round w3-padding-small w3-hover-blue w3-text-center">
                                <i class="fa fa-eye w3-xlarge"></i>
                            </a>
                            <a href="/konyv-szerkesztese/<?= $book["id"] ?>" class="w3-button w3-text-orange w3-border w3-border-orange w3-round w3-padding-small w3-hover-orange w3-text-center" href="">
                                <i class="fa fa-pencil w3-xlarge"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>