<div class="w3-container  w3-margin-bottom-32" id="showcase">
    <h1 class="w3-xxxlarge w3-text-dark-grey w3-center"><b>Szerzők</b></h1>
</div>

<form action="/kereses" method="GET">
    <div class="w3-row-padding w3-margin-bottom">
        <div class="w3-third">
            <input class="w3-input w3-border w3-round " type="text" placeholder="Szerző neve">
        </div>
        <div class="w3-third">
            <button class="w3-button w3-border w3-text-blue w3-border-blue w3-hover-blue w3-round w3-block"><i class="fa fa-search w3-margin-right"></i>Keresés</button>
        </div>
        <div class="w3-third">
            <a href="/uj-szerzo" class="w3-button w3-border w3-text-green w3-border-green w3-hover-green w3-round w3-block"><i class="fa fa-plus w3-margin-right"></i>Új Szerző</a>
        </div>
    </div>
</form>

<div class="w3-container  w3-margin-bottom">
    <div class="w3-responsive w3-card-4">
        <table class="w3-table w3-striped w3-bordered w3-border w3 w3-white ">
            <thead class="w3-dark-grey">
                <th style="width: 10%;">#</th>
                <th style="width: 20%;">Név</th>
                <th style="width: 50%;">Leírás</th>
                <th class="w3-text-center" style="width: 20%;"></th>
            </thead>
            <tbody>
                <?php foreach ($params["authors"] as $author): ?>
                <tr>
                    <td><?= $author["id"] ?></td>
                    <td><?= $author["name"] ?></td>
                    <td><?= substr($author["bio"], 0, 50). "..." ?></td>
                    <td class="w3-center">
                        <a href="/szerzo/<?= $author['id'] ?>" class="w3-button w3-text-blue w3-border w3-border-blue w3-round w3-padding-small w3-hover-blue w3-text-center" href="">
                            <i class="fa fa-eye w3-xlarge"></i>
                        </a>
                        <a href="/szerzo-szerkesztese/<?= $author['id'] ?>"" class="w3-button w3-text-orange w3-border w3-border-orange w3-round w3-padding-small w3-hover-orange w3-text-center">
                            <i class="fa fa-pencil w3-xlarge"></i>
                        </a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>