<div class="w3-container  w3-margin-bottom-32" id="showcase">
    <h1 class="w3-xxxlarge w3-text-dark-grey w3-center"><b>Új Szerző</b></h1>
</div>

<div class="w3-container w3-margin-bottom">
    <div class="w3-responsive w3-card-4 w3-round-large">
        <header class="w3-container w3-dark-grey">
            <h2>Adatok</h2>
        </header>
        <form class="w3-container w3-card-4" method="POST" action="/uj-szerzo">
            <br>
            <p>
                <label class="w3-show-inline-block w3-margin-bottom-8">Név</label>
                <input class="w3-input w3-border" type="text" name="name" minlength="10" required="">
            </p>

            <p>
                <label class="w3-show-inline-block w3-margin-bottom-8">Életrajz</label>
                <textarea class="w3-input w3-border" style="resize:none; height: 300px;" name="bio"></textarea>
            </p>
            <p class="w3-text-center">
                <button type="submit" class="w3-button w3-border w3-green w3-hover-dark-green w3-round w3-block">Felvitel</button>
            </p>
        </form>
    </div>
</div>